default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: "<%= ENV['DATABASE'] %>_development"
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
test:
  <<: *default
  database: "<%= ENV['DATABASE'] %>_test"
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

staging:
  <<: *default
  database: "<%= ENV['DATABASE'] %>_staging"
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

production:
  adapter: postgresql
  encoding: unicode
  database: "<%= ENV['DATABASE'] %>_production"
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['HOST'] %>
  port: 5432
